site_name: TruthSense Documentation

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - System Architecture: architecture.md

  - Audio:
      - Overview: audio/overview.md
      - Pipeline: audio/pipeline.md
      - Transcription: audio/transcription.md
      - Feature Engineering: audio/feature-engineering.md
      - Fluency Model: audio/fluency-model.md
      - Output Schema: audio/output-schema.md
      - CLI: audio/cli.md

  - Video:
      - Overview: video/overview.md
      - Class Structure: video/class-structure.md
      - Setup: video/setup.md
      - Calibration: video/calibration.md
      - Frame Processing: video/process-frame.md
      - Gaze & Eye Contact: video/gaze-eye-contact.md
      - Posture Analysis: video/posture-analysis.md
      - Gesture Analysis: video/gesture-analysis.md
      - Reporting: video/reporting.md
      - CLI: video/cli.md

  - Fusion & LLM: fusion-interface.md
  - LLM Integration: llm-integration.md
  - Frontend Interface: frontend-interface.md
  - API Reference: api-reference.md